
language: python

os: linux

dist: xenial

#branches:
#  only:
#    - master


jobs:
  fast_finish: true
  include:
    # - env:
    #     - TOXENV=docs
    #     - READTHEDOCS=true
    #   name: "Documentation"
    #   python: 3.6
    #   addons:
    #     apt:
    #       packages:
    #         - pandoc
    - env: TOXENV=black
      name: "Black and flake8 compliance"
      python: 3.6
      addons:
        apt:
          packages:
            - libspatialindex-dev
            - libudunits2-dev
    - env: TOXENV=py38
      name: "Python3.8 (Linux)"
      python: 3.8
      addons:
        apt:
          packages:
            - libspatialindex-dev
            - libudunits2-dev
            - libnetcdf-dev
            - libhdf5-dev
    - env: TOXENV=py38-anaconda
      name: "Python3.8 (Linux + Anaconda)"
      python: 3.8
      before_install:
        - printenv
        - wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh
        - bash miniconda.sh -b -p $HOME/miniconda
        - export PATH="$HOME/miniconda/bin:$PATH"
        - hash -r
        - conda config --set always_yes yes --set changeps1 no
        - conda install setuptools
        - conda update -q conda
        - conda create -n dachar -c conda-forge python=$TRAVIS_PYTHON_VERSION
        - source activate dachar
        - conda env update -f environment.yml
        - conda install pytest coveralls pytest-cov xarray mock
      install:
        - conda install pip
        - pip install -e .
      script:
        - py.test --cov dachar
    - env:
        - TOXENV=py37-windows
        - DESIRED_PYTHON=3.7
        - MINICONDA_PATH=$(cygpath --windows /c/miniconda)
      name: "Python3.7 (Windows + Anaconda via Chocolatey)"
      os: windows
      language: shell
      before_install:
        - printenv
        - choco install miniconda3 --params="'/AddToPath:0 /D:$MINICONDA_PATH'"
        - source /c/miniconda/Scripts/activate
        - hash -r
        - conda config --set always_yes yes --set changeps1 no
        - conda install setuptools
        - conda update -q conda
        - conda create -n dachar -c conda-forge python=$DESIRED_PYTHON
        - source activate dachar
        - conda env update -f environment.yml
        - conda install pytest coveralls pytest-cov xarray mock
      install:
        - conda install pip
        - pip install -e .
      script:
        - py.test --cov dachar
    - env: TOXENV=py38-macOS
      name: "Python3.8 (macOS)"
      os: osx
      language: shell
      addons:
        homebrew:
          update: true
          packages:
            - netcdf
            - spatialindex
            - udunits
            - python@3.8
      before_install:
        - printenv
      install:
          - /usr/local/opt/python@3.8/bin/pip3 install -U tox-travis
    - env: TOXENV=py37
      name: "Python3.7 (Linux)"
      python: 3.7
      addons:
        apt:
          packages:
            - libspatialindex-dev
            - libudunits2-dev
    - env: TOXENV=py36
      name: "Python3.6 (Linux)"
      python: 3.6
      addons:
        apt:
          packages:
            - libspatialindex-dev
            - libudunits2-dev
  allow_failures:
      - env: TOXENV=black
      - env: TOXENV=py38-anaconda
      - env: TOXENV=py38-macOS
      - env:
        - TOXENV=py37-windows
        - DESIRED_PYTHON=3.7
        - MINICONDA_PATH=$(cygpath --windows /c/miniconda)

before_install:
    - printenv
    - pip install --upgrade pip

install:
    - pip install -U tox-travis

script: tox -e $TOXENV
